### ISSUE TITLE
Proxy is not compatible with named arguments

### ISSUE THREAD

**Issue by innocenzi** [blood72/laravel-riot-api#3]
Hi,

There is an issue where the `__call` forwarding made by the proxy is not compatible with PHP 8's named arguments:

```php
$matches = LeagueAPI::getMatchIdsByPUUID(
    puuid: $summoner->puuid,
    start: 0,
    count: 1
);
```

![](https://i.imgur.com/SRAOCq3.png)

I think a fix would be as easy as to filtering `null` values from `$parameters`: 

```diff
public function __call($method, $parameters)
{
    if (method_exists($this->api, $method)) {
        $this->modifyParameters($method, $parameters);
    }

-    return $this->api->$method(...$parameters);
+    return $this->api->$method(...array_filter($parameters));
}
```

**Comment by blood72** [comment]
Thank you for reporting!

According to the current error, when using named arguments, 0,1 and 2 ordered pair data are arranged in a posterior row.

If PHP 8 is the standard, the parameter order can be excluded to some extent,  
At least I still plan to support PHP 7.4, so I modified it to suit compatibility.

**Comment by innocenzi** [comment]
Thanks a lot for your quick fix!
